Do not use PersistentDataContainer when not supported
- Versions prior to MC 1.14 do not have the PersistentDataContainer, which caused a `NoSuchMethodError` when trying to get it from the falling block